ifndef::imagesdir[:imagesdir: ../images]
:sectanchors:
:sectlinks:
:icons: font

== C70_001 ユーザー情報更新バッチ
v1.0, 2016-03-15

=== データフロー図
====
.DFD
image::サブdir/mermaid-diagram-20180318003415.svg[]
====
=== 入出力
==== 入力一覧
==== 出力一覧

=== 機能詳細
==== FN001 XXX機能
====
. for (ユーザーリスト) +
+
=====
.. for (契約リスト) +
======
... アカウント識別子をハッシュする +

 absolutely fatal: operation initiation lost in the dodecahedron of doom would you like to die again? y/n +

... if (ハッシュ後のアカウント識別子＝○○） +
+
.データ形式
[format="csv",options="header"]
[frame="topbot",grid="none"]
|======
項目名,設定値,フォーマット,備考
a,b,c,d
A,B,C,D
|======
+
... else +
コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）
コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）コンピュータ言語の大きな分類として、人間が読める言語と読めない言語という分類がある。人間が読める言語は直接人間が使うことを想定して設計しており、人間が読めない言語は（部分的には人間が読める場合もある）「人間による可読性」を犠牲にすることで、よりコンパクトでコンピュータが処理しやすい形式になるよう設計している。（コンピュータ言語に対しては、機械による可読性（機械可読）という観点もある）
======
---
IMPORTANT: 本ブロック内でエラーが発生した場合はWARNログを出力し、処理を中断する。
=====
+
. 応答処理
====

=== インテグレーション
====
asa
.SpringBeans
[plantuml, C70_001_class, png]
....
interface "クラスA" {
	+メソッド1()
}
class "クラスB" {
+メソッド2()
}
class "クラスC" {
}
"クラスA" -- "クラスB"
"クラスA" <|-- "クラスC"
....

====


